In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("VZ Sentiment Data.csv")
df['date'] = pd.to_datetime(df['date']).dt.date
df = df.sort_values(by=['date'])
df.reset_index(drop=True, inplace=True)
df

             date                                              title
0      2020-01-01  TV One remote issues - Verizon FiOS TV | DSLRe...
1      2020-01-01              Verizon 5G Now Hooked Up In 31 Cities
2      2020-01-01  [Channels] No More Fox on FIOS? - Verizon FiOS TV
3      2020-01-01     VZ Stock Rating and Data | Verizonmmunications
4      2020-01-01  FCC chair accuses Verizon of throttling unlimi...
...           ...                                                ...
35306  2026-04-06  Visible’s Pro+ plan is 50% off right now — and...
35307  2026-04-06    Verizon's Visible Smacked 50% Off Its Best Plan
35308  2026-04-06  How Giants Like Amazon And Verizon Find The St...
35309  2026-04-06  U.S. Submarine Cables Market Set for Dynamic E...
35310  2026-04-06  Verizon CEO Daniel Schulman 2025 total compens...

[35311 rows x 2 columns]

In [ ]:
df_removed_pipes = df
df_removed_pipes['title'] = df['title'].str.split('|').str[0]
df_duplicates = df[df_removed_pipes.duplicated()]
df_removed_duplicates = df_removed_pipes.drop_duplicates()
print(df_duplicates)
df_removed_duplicates

             date                                              title
519    2020-01-30  Verizon subscriber addition beats estimates on...
706    2020-02-06  Huawei sues Verizon over alleged patent infrin...
786    2020-02-11                                  Is Verizon down?
787    2020-02-11                                  Is Verizon down?
788    2020-02-11                                  Is Verizon down?
...           ...                                                ...
34598  2026-01-15        Nationwide Verizon Outage Finally Resolved
34599  2026-01-15  Suspected Cause Of Nationwide Verizon Outage R...
34600  2026-01-15        Nationwide Verizon Outage Finally Resolved
34601  2026-01-15        Nationwide Verizon Outage Finally Resolved
34602  2026-01-15        Nationwide Verizon Outage Finally Resolved

[2206 rows x 2 columns]

             date                                              title
0      2020-01-01            TV One remote issues - Verizon FiOS TV
1      2020-01-01              Verizon 5G Now Hooked Up In 31 Cities
2      2020-01-01  [Channels] No More Fox on FIOS? - Verizon FiOS TV
3      2020-01-01                          VZ Stock Rating and Data
4      2020-01-01  FCC chair accuses Verizon of throttling unlimi...
...           ...                                                ...
35306  2026-04-06  Visible’s Pro+ plan is 50% off right now — and...
35307  2026-04-06    Verizon's Visible Smacked 50% Off Its Best Plan
35308  2026-04-06  How Giants Like Amazon And Verizon Find The St...
35309  2026-04-06  U.S. Submarine Cables Market Set for Dynamic E...
35310  2026-04-06  Verizon CEO Daniel Schulman 2025 total compens...

[33105 rows x 2 columns]

In [ ]:
df_removed_duplicates.to_csv("VZ Sentiment Data Removed Duplicates.csv", index=False)